server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.100.196.204:6033/shoppingmall?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nb.entity
logging:
  level:
    com.nb.mapper: debug
